### ISSUE TITLE
"from facebook import pdq" reports error

### ISSUE THREAD

**Issue by likezjuisee** [facebook/ThreatExchange#193] opened 2019-08-12 08:08 UTC
I hava installed from the source code "https://github.com/mobolic/facebook-sdk", but this error happened when I executed the command "from facebook import pdq":
">>> from facebook import pdq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name pdq"

facebook.__version__:'3.2.0-pre'

**Comment by johnkerl** [comment] 2019-08-12 18:21
@likezjuisee the Python code is a bit of an in-progress stub (see also https://github.com/facebook/ThreatExchange/issues/185) -- we shouldn't have included it. :(

There's a pure-Python implementation we can put in there; also we can finish off the Python-to-C++ linkage which (as you found) is incomplete.

**Comment by johnkerl** [comment] 2019-08-12 18:21
I'll close this as a duplicate of https://github.com/facebook/ThreatExchange/issues/185

**Closed** 2019-08-12 18:21 UTC
