### ISSUE TITLE
400 errors from ThreatExchange

### ISSUE THREAD

**Issue by vraja2** [facebook/ThreatExchange#908] opened 2022-01-04 19:38 UTC
We've been noticing errors from ThreatExchange starting December 31st as follows:

```
>>> iter = ThreatDescriptor.objects(since="1641318632", until="1641319052", type_="HASH_MD5", retries=2)
>>> for i in iter:
...     print(i)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vignesh.raja/.pyenv/versions/threatexchange_etl/lib/python3.7/site-packages/pytx/request.py", line 493, in get_generator
    verify=verify)
  File "/Users/vignesh.raja/.pyenv/versions/threatexchange_etl/lib/python3.7/site-packages/pytx/request.py", line 349, in get
    return cls.handle_results(resp)
  File "/Users/vignesh.raja/.pyenv/versions/threatexchange_etl/lib/python3.7/site-packages/pytx/request.py", line 130, in handle_results
    raise pytxFetchError(str(response))
pytx.errors.pytxFetchError: {'status_code': 400, 'url': 'https://graph.facebook.com/v2.9/threat_descriptors/?strict_text=false&type=HASH_MD5&fields=added_on%2Cconfidence%2Cdescription%2Cexpired_on%2Cfirst_active%2Cid%2Cindicator%2Clast_active%2Clast_updated%2Cmetadata%2Cmy_reactions%2Cowner%2Cprecision%2Craw_indicator%2Creview_status%2Cseverity%2Cshare_level%2Csource_uri%2Cstatus%2Ctags%2Ctype&since=1641318632&until=1641319052&include_expired=false&access_token=...%7C996d65915683140cfa3e0139a06a7623', 'message': '(#100) until param is used to limit data by create time and should be provided in seconds since epoch. Did you accidentally use milliseconds?', 'type': 'OAuthException', 'code': 100, 'fbtrace_id': 'A5PfIHmt5Ce2ReyqXnlFYiF'}
```

The `until` param specified is in seconds not milliseconds. Can you please advise? Thanks!

**Comment by BarrettOlson** [comment] 2022-01-04 21:01
Thanks for flagging. Looks like the issue is server side. I am working on a fix and will update the issue once published.

**Comment by Dcallies** [comment] 2022-01-05 15:30
Fix maybe landed last night, and is live, checking on our end... 

Thanks @BarrettOlson!

**Comment by Dcallies** [comment] 2022-01-05 15:33
Using the graph API explorer at https://developers.facebook.com/tools/explorer it looks like its back!

**Closed by Dcallies** 2022-01-05 15:33 UTC
